### ISSUE TITLE
Secondary Navbar

### ISSUE THREAD

**Issue by firnsy** [ballarat-hackerspace/bhack.in#2]
Remove the secondary and tertiary navbars (when logged in) and assimilate the functionality into a drop down menu from the header bar.

So when logged in the primary nav bar reads: Home, About, What, Where, Blog, Username.

Username is a dropdown box that always has Profile and Logout and any other options that are applicable to the roles.

When not logged in, the primary navbar reads: Home, About, What, Where, Blog, Log In

**Comment by Decipher** [comment]
Only Administrators will get the Secondary/Tertiary menu, Super User gets a different one and Authenticated users get none.

There will be more items coming to the Secondary/Tertiary menu (Admin Navbar) that may make it too difficult to remove it, but I'll revisit that in the future.

**Comment by Decipher** [comment]
Opted to use the native Bootstrap menu, with the Administration menu for Administrators.
