### ISSUE TITLE
Google Plus link doesn't work

### ISSUE THREAD

**Issue by robertlayton** [ballarat-hackerspace/bhack.in#20]
1. http://ballarathackerspace.org.au/
2. Click the Google Plus link

The https is the problem, change it to http will fix the issue.

**Comment by Decipher** [comment]
Thanks for reporting @robertlayton.

@scottweston, this appears to be related to the server redirect, can you look into this?

**Comment by Decipher** [comment]
Changed the link on the live site, still need to export.

**Comment by Decipher** [comment]
Exported and pushed to 7.x-1.3.6.
